name: Render README

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/README.template.md'
      - 'tests/example/**' # Trigger when examples change
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install markdown-include

      - name: Render Markdown
        run: |
          python scripts/render_readme.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "docs: update README.md from template" && git push)