name: Engine Tests (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-cpp:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install winlibs
        uses: egor-tensin/setup-mingw@v3
        with:
          platform: x64

      - name: Setup vcpkg
        shell: pwsh
        run: |
          $vcpkgDir = "$env:LOCALAPPDATA/vcpkg"
          if (!(Test-Path $vcpkgDir)) {
            git clone https://github.com/microsoft/vcpkg.git $vcpkgDir
            & "$vcpkgDir/bootstrap-vcpkg.bat"
          }
          echo "VCPKG_ROOT=$vcpkgDir" >> $env:GITHUB_ENV

      - name: Compile C++ Engine
        shell: pwsh
        run: cmake --workflow --preset all --source-dir engines/cpp

      - name: Upload Engine Binary
        uses: actions/upload-artifact@v4
        with:
          name: cpp-engine-binary
          # Matches your preset's binaryDir: ${sourceDir}/build
          path: engines/cpp/build/main.exe
          retention-days: 1

  run-tests:
    needs: build-cpp
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Engine Binary
        uses: actions/download-artifact@v4
        with:
          name: cpp-engine-binary
          path: engines/cpp/build

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run Python Integration Tests
        shell: pwsh
        run: >
          uvx 
          --with pytest 
          --with pytest-rich 
          --with pytest-github-actions-annotate-failures 
          pytest tests/test.py --rich